# Generated by Django 4.0.5 on 2022-07-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corralon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupcor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('pedido', models.CharField(max_length=1000)),
                ('retiro', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
