# Generated by Django 4.0.5 on 2022-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('empaquetado', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=40)),
                ('km', models.IntegerField()),
            ],
        ),
    ]
